title: "maxulysse.github.io"
description: "Interested in Bioinformatics, Reproducible Research, Automation, Data Integration and Visualization..."
baseurl: ""
url: "https://maxulysse.github.io"
words_per_minute : 160

logo:
  path: "/assets/img/favicons/android-chrome-192x192.png"
  width: 192
  height: 192

highlighter: rouge
markdown: kramdown
paginate: 6
permalink: pretty
theme: jekyll-theme-minimal

sass:
  sass_dir: _sass
  style: compact

plugins_dir:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap

include:
  - "_pages"

exclude:
  - [vendor]
  - "LICENSE"
  - "README.md"
  - "assets/mycv/.*"
  - "assets/mycv/*.config"
  - "assets/mycv/*.md"
  - "assets/mycv/*.nf"
  - "assets/mycv/*.tex"
  - "assets/mycv/*.yml"
  - "assets/mycv/*20*.pdf"
  - "assets/mycv/biblio.bib"
  - "assets/mycv/bin/"
  - "assets/mycv/conf/"
  - "assets/mycv/Dockerfile"
  - "assets/mycv/LICENSE"
  - "assets/mycv/pictures/"
  - "assets/mycv/scripts/"
  - "assets/presentations/.*"
  - "assets/presentations/*.md"
  - "assets/presentations/*.tex"
  - "assets/presentations/LICENSE"
  - "assets/presentations/pictures/"
  - "assets/presentations/scripts/"
  - "assets/scripts/test.sh"
